### PR TITLE
Adjust libtype classification according to changes in source classification

### LINKED ISSUE #44: Adjust libtype vocabulary to classification changes in ISIL registry
From https://github.com/hbz/lobid-organisations/issues/116#issuecomment-195422254:

> The values are correctly taken from the ISIL registry. Obviously, they have removed the notation "85" for archive (which still is in the libtype vocab) and added different types of archives to the 5* notations. See the documentation: http://sigel.staatsbibliothek-berlin.de/vergabe/adressenformat/805/#c72416

### PR DESCRIPTION
**Pull request by acka47**
Fixes #44 (and probably also https://github.com/hbz/lobid-organisations/issues/116).

### CODE REVIEW

**Comment by acka47** [comment]
@cKlee Are you knowledgeable regarding the changes in the [organizational type classification of ISIL registry](http://sigel.staatsbibliothek-berlin.de/vergabe/adressenformat/805/#c72416) which this pull request tries to reproduce for the libtype classification used in lobid? If yes, I would be very happy if you could give the changes a quick review.

**Comment by acka47** [comment]
@cklee Have you already asked your colleague (see https://github.com/hbz/lobid-organisations/issues/116#issuecomment-196749170)? Will you review this pull request?

**Comment by cKlee** [comment]
It's all there!

**Comment by acka47** [comment]
Great, thanks. I will merge then and we will proceed with adapting lobid-organisations so that the changes are also reflected in our data.

**Pull request merged**
